### ISSUE TITLE
Shortcuts never load

### ISSUE THREAD

**Issue by tsrats** [SENTINELITE/StreamDeck-Shortcuts#6]
Hello! I have an issue where my shortcuts are never loaded into the streamdeck app. If I add "Launch Shortcut" to a button, Folder, Shortcut, Accessibility, and Override Title only say "Loading...". Any ideas how to resolve this? In system preferences -> security and privacy -> privacy, under automation I have stream deck allowed to control shortcuts.

**Comment by SENTINELITE** [comment]
Hey, @tsrats! 

I just pushed a new version right before you posted this. I had an error when parsing any shortcuts with more than 99 actions. 

If you could restart your StreamDeck Software & make sure the latest version is installed, I'd appreciate it.

Let me know how that goes! 😊

**Comment by tsrats** [comment]
Hi! 

Thanks for the update. Unfortuantly it is still not working for me. I have uninstalled the plugin, quit streamdeck, relaunched streamdeck, and reinstalled the plugin, and it is the same behavior.

**Comment by SENTINELITE** [comment]
Just wanted to update. We found out it was due to Sentry's connection being blocked, via their network environment. Please see issue #7.
